# : Manager [[[

[mgr]
cwd = { fg = "#e2e1ec" }

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#374572", bg = "#374572" }
marker_cut = { fg = "#374572", bg = "#374572" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#b7c5fa", bg = "#b7c5fa" }

# Count
count_copied = { fg = "#dbe1ff", bg = "#374572" }
count_cut = { fg = "#dbe1ff", bg = "#374572" }
count_selected = { fg = "#133801", bg = "#b7c5fa" }

# Border
border_style  = { fg = "#a6d38a" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#a6d38a" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#a6d38a", bg = "#11131a" }
progress_error = { fg = "#ffb4ab", bg = "#11131a" }

# Permissions
perm_type = { fg = "#eab9d1" }
perm_write = { fg = "#b7c5fa" }
perm_exec = { fg = "#ffb4ab" }
perm_read = { fg = "#374572" }
perm_sep = { fg = "#295016" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#a6d38a", fg = "#133801", bold = true }
normal_alt  = { bg = "#434654", fg = "#c4c5d6" }

select_main = { bg = "#eab9d1", fg = "#472638", bold = true }
select_alt  = { bg = "#434654", fg = "#c4c5d6" }

unset_main = { bg = "#b7c5fa", fg = "#202e5a", bold = true }
unset_alt  = { bg = "#434654", fg = "#c4c5d6" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#a6d38a" }
title = {}
value = { fg = "#e2e1ec" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#a6d38a", bold = true, bg = "#11131a" }
inactive = { fg = "#eab9d1", bg = "#11131a" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#a6d38a", bg = "#133801" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#a6d38a" }
title = {}
hovered = { fg = "#374572", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#11131a" }
cand = { fg = "#a6d38a" }
rest = { fg = "#133801" }
desc = { fg = "#e2e1ec" }
separator = " ▶ "
separator_style = { fg = "#e2e1ec" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#a6d38a" }
title    = { fg = "#a6d38a" }
tbl_col  = { fg = "#e2e1ec" }
tbl_cell = { fg = "#e2e1ec", bg = "#11131a" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e1ec" }
run = { fg = "#e2e1ec" }
hovered = { reversed = true, bold = true }
footer = { fg = "#472638", bg = "#eab9d1" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#b7c5fa" }
title_warn = { fg = "#a6d38a" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffdad6", bg = "#93000a" },
    { mime = "application/*exec*", fg = "#ffb4ab" },

    # Fallback
    { url = "*", fg = "#e2e1ec" },
    { url = "*/", fg = "#a6d38a" },
]

# : ]]]
